version: "3.9"

services:
  web:
    build: .
    container_name: flask_api
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://teja:teja@localhost/library
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: library
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
