"""borrowed date column changed to last borrowed date in book invnetory 

Revision ID: 21455e51a79c
Revises: 4af7d79aa10f
Create Date: 2025-04-21 15:41:57.883474

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21455e51a79c'
down_revision = '4af7d79aa10f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_borrowed_date', sa.DateTime(), nullable=True))
        batch_op.drop_column('borrowed_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_inventory', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.drop_column('last_borrowed_date')

    # ### end Alembic commands ###
