"""add indexes

Revision ID: 4384c0c583d8
Revises: b7019165e55c
Create Date: 2025-04-21 21:15:59.382680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4384c0c583d8'
down_revision = 'b7019165e55c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book_inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_book_inventory_book_id'), ['book_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_book_inventory_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_constraint('books_title_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_books_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_title'), ['title'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('users_email_id_key', type_='unique')
        batch_op.drop_constraint('users_username_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_users_email_id'), ['email_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_email_id'))
        batch_op.create_unique_constraint('users_username_key', ['username'])
        batch_op.create_unique_constraint('users_email_id_key', ['email_id'])

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_title'))
        batch_op.drop_index(batch_op.f('ix_books_author'))
        batch_op.create_unique_constraint('books_title_key', ['title'])

    with op.batch_alter_table('book_inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_book_inventory_user_id'))
        batch_op.drop_index(batch_op.f('ix_book_inventory_book_id'))

    # ### end Alembic commands ###
