"""modified and added new fields in book table

Revision ID: b7019165e55c
Revises: 21455e51a79c
Create Date: 2025-04-21 16:02:22.779121

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7019165e55c'
down_revision = '21455e51a79c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_books', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('books_available', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('book_status', sa.String(length=30), nullable=True))
        batch_op.drop_column('books_count')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('books_count', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('book_status')
        batch_op.drop_column('books_available')
        batch_op.drop_column('total_books')

    # ### end Alembic commands ###
